from aiogram import Bot, Dispatcher, executor, types

api_token = '######'
bot = Bot(token=api_token)
dp = Dispatcher(bot)


@dp.message_handler(commands='/start')
async def start(message: types.Message):
    salom = "Istagan davlatingizni yozing, poytaxtini aytaman!"
    await message.answer(f"Salom hurmatli {message.from_user.first_name}👋! {salom}")


@dp.message_handler(content_types='text')
async def test(message: types.Message):
    declarator = {
        "Niderlandiya": 'Amsterdam',
        "Andorra": 'Andorra-la-Velya',
        "Yunoniston": 'Afina',
        "Oʻzbekiston": 'Toshkent',
        "BAA": 'Abu Dabi',
        "Dominikan Respublikasi": 'Santo Domingo',
        "Gretsiya": 'Afina',
        "Serbiya": 'Belgrad',
        "Germaniya": 'Berlin',
        "Shveysariya": 'Bern',
        "Slovakiya": 'Bratislava',
        "Belgiya": 'Brussel',
        "Buyuk Britaniya": "London",
        "britaniya": "London",
        "Vengriya": 'Budapesht',
        "Ruminiya": 'Buxarest',
        "Irlandiya": 'Dublin',
        "Ukraina": 'Kiyev',
        "Moldova": 'Kishinyov',
        "Daniya": 'Kopengagen',
        "Portugaliya": 'Lissabon',
        "Birlashgan Qirollik": 'London',
        "Britaniya": 'London',
        "Sloveniya": 'Lyublyana',
        "Lyuksemburg": 'Lyuksemburg',
        "Ispaniya": 'Madrid',
        "Belarus": 'Minsk',
        "Monako": 'Monako',
        "Rossiya": 'Moskva',
        "Norvegiya": 'Oslo',
        "Fransiya": 'Parij',
        "Chexiya": 'Praga',
        "Islandiya": 'Reykyavik',
        "Latviya": 'Riga',
        "Italiya": 'Rim',
        "San Marino": 'San-Marino',
        "Bosniya": 'Sarayevo',
        "Gertsogovina": 'Sarayevo',
        "Makedoniya": 'Skopye',
        "Bolgariya": 'Sofiya',
        "Shvetsiya": 'Stokgolm',
        "Estoniya": 'Tallin',
        "Albaniya": 'Tirana',
        "Lixtenshteyn": 'Vaduts',
        "Malta": 'Valletta',
        "Polsha": 'Varshava',
        "Vatikan": 'Vatikan',
        "Avstriya": 'Vena',
        "Litva": 'Vilnyus',
        "Finlandiya": 'Helsinki',
        "Xorvatiya": 'Zagreb',
        "Malta ordeni": 'Malta qasri*',
        "Chernogoriya": 'Podgoritsa/Setine*',
        "Kosovo": 'Prishtina*',
        "Dnestr bo'yi Moldova Respublikasi": 'Tiraspol*',

        "Birlashgan Arab Amirliklari": "Abu Dabi",
        "Iordaniya": "Amman	",
        "Turkiya": "Anqara",
        "Turkmaniston": "Ashxobod",
        "Iroq": "Bagʻdod	",
        "Ozarbayjon": "Boku",
        "Tailand": "Bangkok	 ",
        "Bruney": "Bandar-Seri-Begavan",
        "Livan": "Bayrut",
        "Qirgʻiziston": "Bishkek",
        "Laos": "Ventyan",
        "Bangladesh": "Dakka",
        "Suriya": "Damashq",
        "Hindiston": "Dehli (Nyu Dehli)",
        "Indoneziya": "Jakarta",
        "Sharqiy Timor": "Dili",
        "Qatar": "Doha",
        "Tojikiston": "Dushanbe",
        "Armaniston": "Yerevan",
        "Isroil": "Quddus",
        "Pokiston": "Islomobod",
        "Afgʻoniston": "Qobul	",
        "Nepal": "Katmandu",
        "Malayziya": "Kuala Lumpur",
        "Maldivalar": "Male",
        "Bahrayn": "Manama",
        "Filippin": "Manila",
        "Oman": "Maskat",
        "Myanma": "Neypido",
        "Qibris": "Nikosiya",
        "Qozogʻiston": "Nur-Sulton",
        "Xitoy": "Pekin",
        "Kambodja": "Pnompen",
        "Shimoliy Koreya": "Pxenyan	",
        "Yaman": "Sano",
        "Janubiy Koreya": "Seul",
        "Singapur": "Singapur",
        "O'zbekiston": "Toshkent",
        "Uzbekistan": "Toshkent",
        "AQSH": "Washington",
        "Gruziya": "Tbilisi",
        "Eron": "Tehron",
        "Yaponiya": "Tokio",
        "Butan": "Thimphu",
        "Moʻgʻuliston": "Ulan-Bator",
        "Vyetnam": "Xanoy",
        "Shri Lanka": "Shri-Jayavardenepura-Kotte",
        "Quvayt": "Al-Quvayt",
        "Saudiya Arabistoni": "Ar-Riyod",
        "Shimoliy Kipr": "Lefkosiya*",
        "Falastin": "Ramalla*",
        "Abxaziya": "Suxumi*",
        "Tayvan": "Taybey*",
        "Janubiy Osetiya": "Sxinval*",
        "Nigeriya": "Abuja",
        "Efiopiya": "Addis-Abeba",
        "Gana": "Akkra",
        "Jazoir": "Jazoir (shahar)",
        "Madagaskar": "Antananarivu",
        "Eritreya": "Asmera",
        "Mali": "Bamako",
        "Markaziy Afrika Respublikasi": "Bangi",
        "Gambiya": "Banjul",
        "Gvineya-Bisau": "Bissau",
        "Kongo Respublikasi": "Brazzavil",
        "Burundi": "Bujumbura",
        "Seyshell orollari": "Viktoriya",
        "Namibiya": "Vindxuk",
        "Botsvana": "Gaborone",
        "Senegal": "Dakar",
        "Jibuti": "Jibuti shahri",
        "Janubiy Sudan": "Juba",
        "Tanzaniya": "Dodoma",
        "Misr": "Qohira",
        "Uganda": "Kampala",
        "Ruanda": "Kigali",
        "Kongo DR": "Kinshasa",
        "Kongo Demokratik Respublikasi": "Kinshasa",
        "Gvineya": "Konakri",
        "Gabon": "Librevil",
        "Malavi": "Lilongve",
        "Togo": "Lome",
        "Angola": "Luanda",
        "Zambiya": "Lusaka",
        "Ekvatorial Gvineya": "Malabo",
        "Mozambik": "Maputu",
        "Lesoto": "Maseru",
        "Esvatini": "Mbabane",
        "Somali": "Mogadisho",
        "Liberiya": "Monroviya",
        "Komoros": "Moroni",
        "Keniya": "Nayrobi",
        "Chad": "Njamena",
        "Niger": "Niamey",
        "Mavritaniya": "Nuakshot",
        "Mavrikiy": "Port-Lui",
        "Benin": "Porto-Novo",
        "Kabo Verde": "Praya",
        "Janubiy Afrika": "Pretoriya",
        "Marokash": "Rabot",
        "San Tome": "San-Tome",
        "Liviya": "Tripoli",
        "Tunis": "Tunis shahri",
        "Burkina Faso": "Uagadugu",
        "Syerra Leone": "Fritaun",
        "Zimbabve": "Xarare",
        "Sudan": "Xartum",
        "Kot-d'Ivuar": "Yamusukro",
        "Kamerun": "Yaunde",
        "Puntlend": "Garove",
        "Azavad": "Timbuktu",
        "Somalilend": "Xargeysa",
        "Sahroi Arab Demokratik Respublikasi": "El-Ayun, Bir-Lelu",
        "Paragvay": "Asunson",
        "Sent Kitts va Nevis": "Baster",
        "Beliz": "Belmopan",
        "Kolumbiya": "Bogota",
        "Braziliya": "Brazilia",
        "Barbados": "Bridjtaun",
        "Argentina": "Buenos Ayres",
        "AQSh": "Vashington",
        "Kuba": "Gavana",
        "Gvatemala": "Gvatemala shahri",
        "Gayana": "Jorjtaun",
        "Venesuela": "Karakas",
        "Sent Lusiya": "Kastri",
        "Sent Vinsent va Grenadinlar": "Kingstaun",
        "Yamayka": "Kingston",
        "Ekvador": "Kito",
        "Peru": "Lima",
        "Nikaragua": "Managua",
        "Meksika": "Mexiko",
        "Urugvay": "Montevideo",
        "Bagam orollari": "Nassau",
        "Kanada": "Ottava",
        "Panama": "Panama",
        "Surinam": "Paramaribo",
        "Gaiti": "Port-o-Prens",
        "Trinidad va Tobago": "Port-of-Speyn",
        "Dominikan": "Rozo",
        "El Salvador": "San Salvador",
        "Kosta Rika": "San Xose",
        "Dominika Respublikasi": "Santo Domingo",
        "Chili": "Santyago",
        "Antigua va Barbuda": "Sent Jons",
        "Grenada": "Sent Jorjes",
        "Boliviya": "Sukre",
        "Gonduras": "Tegusigalpa",
        "Samoa": "Apia",
        "Yangi Zelandiya": "Vellington",
        "Avstraliya": "Kanberra",
        "Marshall Orollari": "Majuro",
        "Palau": "Ngerulmud",
        "Tonga": "Nukualofa",
        "Mikroneziya": "Palikir",
        "Vanuatu": "Port-Vila",
        "Papua Yangi Gvineya": "Port-Morsbi",
        "Fiji": "Suva",
        "Tuvalu": "Funafuti",
        "Solomon Orollari": "Xoniara",
        "Kiribati": "Janubiy Tarava (Bayriki)",
    }

    text = message.text.title()
    num = []
    num1 = []
    for i, j in declarator.items():
        num.append(i.title())
        num1.append(j.title().strip())

    if text in num:
        name1 = num.index(text)
        await message.answer(f"<[{text}]> davlatini poytaxti 👉{num1[name1]}👈 shaxri")
    else:
        await message.answer(f"Siz sintaktik xatolik qildingiz <[{text}]>🧐 Yoki bunday davlat haqida ma'lumot yo'q🙁")


if __name__ == "__main__":
    executor.start_polling(dp)
